config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
      get '/reviews/new' => 'reviews#new'
      post '/reviews' => 'reviews#create'
    end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy



  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["japanese", "italian", "french", "belgian", "chinese"], allow_nil: false }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant


  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }, numericality: true
  validates :restaurant_id, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @review = Review.new
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_restaurant, only: [ :new, :create ]

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsYelpMvp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navbar'  %>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div id="banner">
  <h1>Discover</h1>
</div>



<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone number</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td class="wide"><%= restaurant.name %></td>
        <td class="wide"><%= restaurant.address %></td>
        <td class="wide"><%= restaurant.phone_number %></td>
        <td class="wide"><%= restaurant.category %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= @restaurant.phone_number %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @restaurant.category %>
  </p>

  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
  <%= link_to 'Back', restaurants_path %> |
  <%= link_to 'Review', restaurant_reviews_new_path(@restaurant) %>


  <%= render 'reviews/form_review'  %>

  <h3>Reviews</h3>

  <ul class="list-unstyled">
    <% @restaurant.reviews.each do |review| %>
      <li>
        <% review.rating.times do%>
          <i class="fa fa-star" aria-hidden="true"></i>
        <% end %>
        <% (5-review.rating).times do%>
          <i class="fa fa-star-o" aria-hidden="true"></i>
        <% end %>
       <%= review.content %></li>
    <% end %>
  </ul>
</div>

app/views/reviews/_form_review.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.text_field :content, placeholder: "Content" %>
  <%= f.number_field :rating, placeholder: "Rating 1 - 5" %>
  <%= f.submit "add a review" %>
<% end %>

app/views/reviews/new.html.erb
<h1>Say what you have to say!!!!</h1>

<%= render 'form_review'  %>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
    <div class="nav-item">
      <%= link_to image_tag('home.png'), restaurants_path, class: 'navbar-wagon-brand' %>
    </div>

    <div class="navbar-wagon-right">
      <%= link_to "New Restaurant", new_restaurant_path, class: 'btn btn-primary' %>
    </div>
</nav>